version: '3.8'

services:
  # Matreshka Core System - Production Ready
  matreshka-core:
    build:
      context: .
      target: production
      args:
        - NODE_ENV=production
    image: matreshka-arbitrage:2.0.0
    container_name: matreshka-core
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - DEMO_MODE=true
      - WEB_PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=matreshka
      - DB_USER=matreshka
      - DB_PASSWORD=matreshka
      - HUMMINGBOT_HOST=hummingbot-gateway
      - HUMMINGBOT_PORT=8080
      # Security settings
      - RATE_LIMIT_WINDOW=900000
      - RATE_LIMIT_MAX_REQUESTS=1000
      # Performance settings
      - HEALTH_CHECK_INTERVAL=30000
      - PERFORMANCE_LOG_INTERVAL=300000
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs:rw
      - ./config:/app/config:ro
      - ./data:/app/data:rw
    restart: unless-stopped
    networks:
      - matreshka-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "node", "dist/index.js", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Hummingbot Gateway
  hummingbot-gateway:
    image: hummingbot/gateway:latest
    ports:
      - "8080:8080"
    environment:
      - GATEWAY_PASSPHRASE=your-secure-passphrase
      - GATEWAY_PORT=8080
    volumes:
      - ./hummingbot-gateway/conf:/home/hummingbot/gateway/conf
      - ./hummingbot-gateway/logs:/home/hummingbot/gateway/logs
    restart: unless-stopped
    networks:
      - matreshka-network

  # Hummingbot Instance 1 (Maker)
  hummingbot-maker:
    image: hummingbot/hummingbot:latest
    environment:
      - CONFIG_FILE_NAME=dman_strategy_config.yml
      - TEMPLATE=dman_v2
    volumes:
      - ./hummingbot-instances/maker/conf:/home/hummingbot/conf
      - ./hummingbot-instances/maker/data:/home/hummingbot/data
      - ./hummingbot-instances/maker/logs:/home/hummingbot/logs
    depends_on:
      - hummingbot-gateway
    restart: unless-stopped
    networks:
      - matreshka-network

  # Hummingbot Instance 2 (Taker)
  hummingbot-taker:
    image: hummingbot/hummingbot:latest
    environment:
      - CONFIG_FILE_NAME=dman_taker_config.yml
      - TEMPLATE=dman_v2
    volumes:
      - ./hummingbot-instances/taker/conf:/home/hummingbot/conf
      - ./hummingbot-instances/taker/data:/home/hummingbot/data
      - ./hummingbot-instances/taker/logs:/home/hummingbot/logs
    depends_on:
      - hummingbot-gateway
    restart: unless-stopped
    networks:
      - matreshka-network

  # Redis for caching and inter-service communication
  redis:
    image: redis:7-alpine
    container_name: matreshka-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    networks:
      - matreshka-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # PostgreSQL for persistent data
  postgres:
    image: postgres:15-alpine
    container_name: matreshka-postgres
    environment:
      - POSTGRES_DB=matreshka
      - POSTGRES_USER=matreshka
      - POSTGRES_PASSWORD=matreshka
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    restart: unless-stopped
    networks:
      - matreshka-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U matreshka -d matreshka"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  # Grafana for monitoring
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana:/etc/grafana/provisioning
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - matreshka-network

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - matreshka-network

volumes:
  redis_data:
  postgres_data:
  grafana_data:
  prometheus_data:

networks:
  matreshka-network:
    driver: bridge
